const API_ENDPOINTS = {
  MAIN: {
    DEFAULT: "/api",
  },
  USER: {
    LOGIN: "/user/login",
    REGISTER: "/user/register",
    ALL: "/user/get/all",
    USER: "/user/get",
    SINGLE: "/user/get/:id",
    UPDATE: "/user/update/:id",
    DELETE: "/user/delete/:id",
    SEARCH: "/user/search",
    CURRENT: "/user/current",
    RESET_PASSWORD: "/user/reset-password",
  },
  ADMIN: {
    LOGIN: "/admin/login",
    REGISTER: "/admin/register",
    ALL: "/user/get/all",
    ADMIN: "/admin/get",
    SINGLE: "/user/get/:id",
    UPDATE: "/user/update/:id",
    DELETE: "/user/delete/:id",
    SEARCH: "/user/search",
    CURRENT: "/user/current",
    RESET_PASSWORD: "/user/reset-password",
  },
  PROFESSOR: {
    LOGIN: "/professor/login",
    REGISTER: "/professor/register",
    ALL: "/professor/get/all",
    USER: "/professor/get",
    SINGLE: "/professor/get/:id",
    UPDATE: "/professor/update/:id",
    DELETE: "/professor/delete/:id",
    SEARCH: "/professor/search",
    CURRENT: "/professor/current",
    RESET_PASSWORD: "/user/reset-password",
  },
  STAFF: {
    LOGIN: "/staff/login",
    REGISTER: "/staff/register",
    ALL: "/staff/get/all",
    USER: "/staff/get",
    SINGLE: "/staff/get/:id",
    UPDATE: "/staff/update/:id",
    DELETE: "/staff/delete/:id",
    SEARCH: "/staff/search",
    CURRENT: "/staff/current",
    RESET_PASSWORD: "/staff/reset-password",
  },
  ATTENDANCE: {
    ATTENDANCE: "/attendance/attendance",
    GET: "/attendance/get/summary",
    GETTODAY: "/attendance/get-today",
    ATTENDANCESTATS: "/attendance/stats",
    GETUSERATTENDANCE: "/attendance/user/:id",
    GETSUMMARYEVERYDAY: "/attendance/get/summary/daily",
    GETPRESENTBYDATE: "/attendance/get/present/by-date",
  },
  SCHEDULE: {
    CREATE: "/schedule/create",
    GET: "/schedule/get",
    UPDATE: "/schedule/update/:id",
    DELETE: "/schedule/delete/:id",
    GETTODAY: "/attendance/get-today",
    ATTENDANCESTATS: "/attendance/stats",
    GETUSERATTENDANCE: "/attendance/user/:id",
  },
};

module.exports = API_ENDPOINTS; // ← ✅ CommonJS export
